-- Chuẩn hóa trạng thái giao hàng legacy về enum hiện tại
-- Để tránh lỗi parse enum như: PENDING_CONFIRMATION, SHIPPING, COMPLETED...

-- delivery.current_status
UPDATE delivery
SET current_status = CASE UPPER(current_status)
    WHEN 'PENDING_CONFIRMATION' THEN 'PENDING'
    WHEN 'SHIPPER_ASSIGNED' THEN 'READY_TO_SHIP'
    WHEN 'PICKED_UP' THEN 'SHIPPED'
    WHEN 'SHIPPING' THEN 'DELIVERING'
    WHEN 'IN_TRANSIT' THEN 'DELIVERING'
    WHEN 'NEARBY' THEN 'DELIVERING'
    WHEN 'COMPLETED' THEN 'DELIVERED'
    WHEN 'DELIVERY_FAILED' THEN 'FAILED'
    WHEN 'RETURNED' THEN 'FAILED'
    ELSE UPPER(current_status)
END
WHERE current_status IS NOT NULL;

-- delivery_status_history.status
UPDATE delivery_status_history
SET status = CASE UPPER(status)
    WHEN 'PENDING_CONFIRMATION' THEN 'PENDING'
    WHEN 'SHIPPER_ASSIGNED' THEN 'READY_TO_SHIP'
    WHEN 'PICKED_UP' THEN 'SHIPPED'
    WHEN 'SHIPPING' THEN 'DELIVERING'
    WHEN 'IN_TRANSIT' THEN 'DELIVERING'
    WHEN 'NEARBY' THEN 'DELIVERING'
    WHEN 'COMPLETED' THEN 'DELIVERED'
    WHEN 'DELIVERY_FAILED' THEN 'FAILED'
    WHEN 'RETURNED' THEN 'FAILED'
    ELSE UPPER(status)
END
WHERE status IS NOT NULL;
