ALTER TABLE delivery
    ADD COLUMN shipping_provider VARCHAR(100) NULL AFTER current_status,
    ADD COLUMN tracking_code VARCHAR(120) NULL AFTER shipping_provider,
    ADD COLUMN tracking_url VARCHAR(500) NULL AFTER tracking_code,
    ADD COLUMN shipped_at DATETIME NULL AFTER tracking_url,
    ADD COLUMN shipping_note TEXT NULL AFTER delivered_at;

UPDATE delivery
SET current_status = CASE current_status
    WHEN 'PENDING_CONFIRMATION' THEN 'PENDING'
    WHEN 'CONFIRMED' THEN 'CONFIRMED'
    WHEN 'PREPARING' THEN 'PREPARING'
    WHEN 'READY_TO_SHIP' THEN 'READY_TO_SHIP'
    WHEN 'SHIPPER_ASSIGNED' THEN 'READY_TO_SHIP'
    WHEN 'PICKED_UP' THEN 'SHIPPED'
    WHEN 'IN_TRANSIT' THEN 'DELIVERING'
    WHEN 'NEARBY' THEN 'DELIVERING'
    WHEN 'DELIVERED' THEN 'DELIVERED'
    WHEN 'DELIVERY_FAILED' THEN 'FAILED'
    WHEN 'RETURNED' THEN 'FAILED'
    WHEN 'CANCELLED' THEN 'CANCELLED'
    ELSE current_status
END;
